name: Release

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: cargo build --locked --verbose --release
      env:
        OPENSSL_STATIC: 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: rojo-linux
        path: target/release/rojo
